"""empty message

Revision ID: da64e6da27d5
Revises: 4767e3dd1cfa
Create Date: 2016-02-25 17:17:04.935833

"""

# revision identifiers, used by Alembic.
revision = 'da64e6da27d5'
down_revision = '4767e3dd1cfa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('query', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_user',
    sa.Column('source_slug', sa.Unicode(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_slug'], ['source.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('selector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Unicode(), nullable=True),
    sa.Column('normalized', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('entity_id', sa.Unicode(length=50), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selector_normalized'), 'selector', ['normalized'], unique=False)
    op.create_index(op.f('ix_selector_text'), 'selector', ['text'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selector_text'), table_name='selector')
    op.drop_index(op.f('ix_selector_normalized'), table_name='selector')
    op.drop_table('selector')
    op.drop_table('source_user')
    op.drop_table('alert')
    ### end Alembic commands ###
