"""empty message

Revision ID: da64e6da27d5
Revises: 4767e3dd1cfa
Create Date: 2016-02-25 17:17:04.935833

"""

# revision identifiers, used by Alembic.
revision = 'da64e6da27d5'
down_revision = '4767e3dd1cfa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('query', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selector_text'), table_name='selector')
    op.drop_index(op.f('ix_selector_normalized'), table_name='selector')
    op.drop_table('selector')
    op.drop_table('source_user')
    op.drop_table('alert')
    ### end Alembic commands ###
